server:
  port: 8089


spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://182.92.241.132:3306/my_site?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&verifyServerCertificate=false&useSSL=false
          username: root
          password: mac123
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

    #redis配置
    redis:
      host: 182.92.241.132
      port: 6379
      password: 123456

    thymeleaf:
            prefix: classpath:/templates/
            check-template-location: true
            suffix: .html
            encoding: UTF-8
            mode: LEGACYHTML5
            cache: false
    aop:
      auto: true
      proxy-target-class: true
    servlet:
          multipart:
            max-file-size: 10MB
            max-request-size: 100MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.luischen.model


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    cn.luischen.dao : DEBUG

swagger:
  show: true

qiniu:
  accesskey: ""
  serectkey: ""
  bucket: ""
  cdn:
    url: ""

#微信相关
wx:
  # 公众号配置(必填)
  mp:
    app-id: wxd96d03276b987fdb
    secret: 8ed81ed13cfa180f2a08d56dc8ef1759
    token: kpcmcn
    aes-key: xx

    # 存储配置redis(可选)
    config-storage:
      type: RedisTemplate
      key-prefix: wx
      redis:
        host: 182.92.241.132
        port: 6379
        password: 123456

      # http客户端配置
      http-client-type: HttpClient
      http-proxy-host:
      http-proxy-port:
      http-proxy-username:
      http-proxy-password: